Repository SS-Soon-Senior/HanaroWa-BE, pull requests merged in 2025-08, with the labels that each got.

#20 Feat: AdminLesson
  src/main/java/com/ss/hanarowa/admin/controller/AdminController.java
  src/main/java/com/ss/hanarowa/admin/dto/response/AdminLessonListResponseDTO.java
  src/main/java/com/ss/hanarowa/admin/service/AdminService.java
  src/main/java/com/ss/hanarowa/admin/service/impl/AdminServiceImpl.java
  src/main/java/com/ss/hanarowa/lesson/repository/LessonRepository.java
  src/main/java/com/ss/hanarowa/security/JwtAuthenticationFilter.java
  src/main/resources/application.properties
Labels: 🚀 feat

#22 fix: repository 잘못된 entitiy 이름 변경
  src/main/java/com/ss/hanarowa/domain/lesson/repository/RoomTimeRepository.java
  src/main/java/com/ss/hanarowa/domain/member/repository/MyLessonRepository.java
Labels: ⭐️ fix

#23 Refactor: DeleteAdminFolder
  src/main/java/com/ss/hanarowa/domain/admin/service/AdminService.java
  src/main/java/com/ss/hanarowa/domain/lesson/controller/AdminController.java
  src/main/java/com/ss/hanarowa/domain/lesson/dto/response/AdminLessonListResponseDTO.java
  src/main/java/com/ss/hanarowa/domain/lesson/service/AdminService.java
  src/main/java/com/ss/hanarowa/domain/lesson/service/impl/AdminServiceImpl.java
Labels: ✨refactor

#24 Feat:회원탈퇴 구현
  src/main/java/com/ss/hanarowa/domain/facility/controller/FacilityController.java
  src/main/java/com/ss/hanarowa/domain/member/controller/AuthController.java
  src/main/java/com/ss/hanarowa/domain/member/controller/MemberController.java
  src/main/java/com/ss/hanarowa/domain/member/entity/Member.java
  src/main/java/com/ss/hanarowa/domain/member/service/MemberService.java
  src/main/java/com/ss/hanarowa/domain/member/service/impl/MemberServiceImpl.java
Labels: 🚀 feat

#26 Fix: AdminLesson
  src/main/java/com/ss/hanarowa/domain/lesson/controller/AdminController.java
  src/main/java/com/ss/hanarowa/domain/member/dto/MemberAuthDTO.java
  src/main/java/com/ss/hanarowa/global/security/JwtAuthenticationFilter.java
Labels: ⭐️ fix

#32 Feat: branch 선택/수정& GeneralException 처리
  src/main/java/com/ss/hanarowa/domain/branch/controller/BranchController.java
  src/main/java/com/ss/hanarowa/domain/member/controller/MemberController.java
  src/main/java/com/ss/hanarowa/domain/member/service/MemberService.java
  src/main/java/com/ss/hanarowa/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/ss/hanarowa/global/exception/ExceptionAdvice.java
  src/main/java/com/ss/hanarowa/global/response/code/status/ErrorStatus.java
Labels: 🚀 feat

#36 fix: 로그인 쓸데없는 코드 제거 및 정리
  src/main/java/com/ss/hanarowa/global/config/CustomSecurityConfig.java
  src/main/java/com/ss/hanarowa/global/security/JwtAuthenticationFilter.java
  src/main/java/com/ss/hanarowa/global/security/handler/CustomAccessDeiniedHandler.java
Labels: ⭐️ fix

#39 Feat: 관리자 회원목록
  src/main/java/com/ss/hanarowa/domain/member/controller/AdminMemberController.java
  src/main/java/com/ss/hanarowa/domain/member/controller/AuthController.java
  src/main/java/com/ss/hanarowa/domain/member/controller/MemberController.java
  src/main/java/com/ss/hanarowa/domain/member/dto/request/LoginRequestDTO.java
  src/main/java/com/ss/hanarowa/domain/member/dto/request/ModifyPasswdRequestDTO.java
  src/main/java/com/ss/hanarowa/domain/member/dto/response/MemberListResponseDTO.java
  src/main/java/com/ss/hanarowa/domain/member/repository/MemberRepository.java
  src/main/java/com/ss/hanarowa/domain/member/service/AdminMemberService.java
  src/main/java/com/ss/hanarowa/domain/member/service/MemberService.java
  src/main/java/com/ss/hanarowa/domain/member/service/impl/AdminMemberServiceImpl.java
  src/main/java/com/ss/hanarowa/domain/member/service/impl/MemberServiceImpl.java
Labels: 🚀 feat

#41 Fix : Member controller 수정
  src/main/java/com/ss/hanarowa/domain/facility/dto/request/FacilityReservationDTO.java
  src/main/java/com/ss/hanarowa/domain/facility/service/impl/FacilityServiceImpl.java
  src/main/java/com/ss/hanarowa/domain/member/controller/AuthController.java
  src/main/java/com/ss/hanarowa/domain/member/controller/MemberController.java
  src/main/java/com/ss/hanarowa/domain/member/dto/request/MemberInfoRequestDTO.java
  src/main/java/com/ss/hanarowa/domain/member/dto/request/MemberRegistRequestDTO.java
  src/main/java/com/ss/hanarowa/domain/member/dto/response/MemberAuthResponseDTO.java
  src/main/java/com/ss/hanarowa/domain/member/service/MemberService.java
  src/main/java/com/ss/hanarowa/domain/member/service/impl/CustomUserDetailsService.java
  src/main/java/com/ss/hanarowa/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/ss/hanarowa/global/exception/ExceptionAdvice.java
  src/main/java/com/ss/hanarowa/global/response/code/status/ErrorStatus.java
  src/main/java/com/ss/hanarowa/global/security/JwtAuthenticationFilter.java
  src/main/java/com/ss/hanarowa/global/security/JwtUtil.java
Labels: ⭐️ fix

#42 Feat: LessonDetail
  src/main/java/com/ss/hanarowa/domain/lesson/controller/AdminLessonController.java
  src/main/java/com/ss/hanarowa/domain/lesson/controller/LessonController.java
  src/main/java/com/ss/hanarowa/domain/lesson/dto/response/LessonGisuResponseDTO.java
  src/main/java/com/ss/hanarowa/domain/lesson/dto/response/LessonMoreDetailResponseDTO.java
  src/main/java/com/ss/hanarowa/domain/lesson/dto/response/ReviewResponseDTO.java
  src/main/java/com/ss/hanarowa/domain/lesson/entity/Lesson.java
  src/main/java/com/ss/hanarowa/domain/lesson/entity/Review.java
  src/main/java/com/ss/hanarowa/domain/lesson/repository/ReviewRepository.java
  src/main/java/com/ss/hanarowa/domain/lesson/service/LessonService.java
  src/main/java/com/ss/hanarowa/domain/lesson/service/ReviewService.java
  src/main/java/com/ss/hanarowa/domain/lesson/service/impl/LessonServiceImpl.java
  src/main/java/com/ss/hanarowa/domain/lesson/service/impl/ReviewServiceImpl.java
  src/main/java/com/ss/hanarowa/domain/member/entity/MyLesson.java
  src/main/java/com/ss/hanarowa/domain/member/repository/MyLessonRepository.java
Labels: 🚀 feat

#43 Feat: ai 관련 api 를 모두 생성
  .gitignore
  build.gradle
  src/main/java/com/ss/hanarowa/domain/ai/client/GeminiApiClient.java
  src/main/java/com/ss/hanarowa/domain/ai/controller/AIController.java
  src/main/java/com/ss/hanarowa/domain/ai/dto/CourseRecommendation.java
  src/main/java/com/ss/hanarowa/domain/ai/dto/JobRecommendation.java
  src/main/java/com/ss/hanarowa/domain/ai/dto/request/CourseRecRequestDto.java
  src/main/java/com/ss/hanarowa/domain/ai/dto/request/GeminiRequestDto.java
  src/main/java/com/ss/hanarowa/domain/ai/dto/request/JobRecRequestDto.java
  src/main/java/com/ss/hanarowa/domain/ai/dto/response/CourseRecResponseDto.java
  src/main/java/com/ss/hanarowa/domain/ai/dto/response/GeminiResponseDto.java
  src/main/java/com/ss/hanarowa/domain/ai/dto/response/JobRecResponseDto.java
  src/main/java/com/ss/hanarowa/domain/ai/service/AIRecService.java
  src/main/java/com/ss/hanarowa/domain/ai/service/impl/AIRecServiceImpl.java
  src/main/java/com/ss/hanarowa/global/response/code/status/ErrorStatus.java
Labels: 🚀 feat

#45 Feat: 지점별 강좌 리스트 조회
  src/main/java/com/ss/hanarowa/domain/lesson/controller/LessonController.java
  src/main/java/com/ss/hanarowa/domain/lesson/dto/response/LessonInfoResponseDTO.java
  src/main/java/com/ss/hanarowa/domain/lesson/dto/response/LessonListByBranchIdResponseDTO.java
  src/main/java/com/ss/hanarowa/domain/lesson/repository/LessonRepository.java
  src/main/java/com/ss/hanarowa/domain/lesson/service/LessonService.java
  src/main/java/com/ss/hanarowa/domain/lesson/service/impl/AdminLessonServiceImpl.java
  src/main/java/com/ss/hanarowa/domain/lesson/service/impl/LessonServiceImpl.java
Labels: 🚀 feat

#47 Feat: 강좌&강사명 강좌 목록 검색 API 구현
  src/main/java/com/ss/hanarowa/domain/lesson/controller/LessonController.java
  src/main/java/com/ss/hanarowa/domain/lesson/dto/response/LessonListSearchResponseDTO.java
  src/main/java/com/ss/hanarowa/domain/lesson/repository/LessonRepository.java
  src/main/java/com/ss/hanarowa/domain/lesson/service/LessonService.java
  src/main/java/com/ss/hanarowa/domain/lesson/service/impl/LessonServiceImpl.java
Labels: 🚀 feat

#49 Feat: 개설 / 신청 강좌 목록 조회 생성
  src/main/java/com/ss/hanarowa/domain/lesson/controller/LessonController.java
  src/main/java/com/ss/hanarowa/domain/lesson/dto/request/AppliedLessonRequestDTO.java
  src/main/java/com/ss/hanarowa/domain/lesson/dto/request/OfferedLessonRequestDTO.java
  src/main/java/com/ss/hanarowa/domain/lesson/dto/response/AppliedLessonListResponseDTO.java
  src/main/java/com/ss/hanarowa/domain/lesson/dto/response/LessonListResponseDTO.java
  src/main/java/com/ss/hanarowa/domain/lesson/dto/response/OfferedLessonListResponseDTO.java
  src/main/java/com/ss/hanarowa/domain/lesson/entity/Lesson.java
  src/main/java/com/ss/hanarowa/domain/lesson/entity/LessonGisu.java
  src/main/java/com/ss/hanarowa/domain/lesson/repository/LessonRepository.java
  src/main/java/com/ss/hanarowa/domain/lesson/service/LessonService.java
  src/main/java/com/ss/hanarowa/domain/lesson/service/impl/LessonServiceImpl.java
  src/main/java/com/ss/hanarowa/domain/member/repository/MyLessonRepository.java
  src/main/java/com/ss/hanarowa/global/entity/BaseEntity.java
  src/main/java/com/ss/hanarowa/global/response/code/status/ErrorStatus.java
Labels: 🚀 feat

#51 Feat: 관리자 시설 예약 내역 조회 API
  src/main/java/com/ss/hanarowa/domain/facility/controller/AdminFacilityController.java
  src/main/java/com/ss/hanarowa/domain/facility/controller/FacilityController.java
  src/main/java/com/ss/hanarowa/domain/facility/dto/reponse/AdminFacilityResponseDTO.java
  src/main/java/com/ss/hanarowa/domain/facility/repository/FacilityTimeRepository.java
  src/main/java/com/ss/hanarowa/domain/facility/service/FacilityService.java
  src/main/java/com/ss/hanarowa/domain/facility/service/impl/FacilityServiceImpl.java
Labels: 🚀 feat

#52 Feat: 강좌 신청, 신청 취소 api 생성
  src/main/java/com/ss/hanarowa/domain/lesson/controller/LessonController.java
  src/main/java/com/ss/hanarowa/domain/lesson/service/LessonService.java
  src/main/java/com/ss/hanarowa/domain/lesson/service/impl/LessonServiceImpl.java
  src/main/java/com/ss/hanarowa/global/response/code/status/ErrorStatus.java
Labels: 🚀 feat

#53 Fix: 신청 강좌 목록 조회 수정
  src/main/java/com/ss/hanarowa/domain/lesson/controller/LessonController.java
  src/main/java/com/ss/hanarowa/domain/lesson/dto/request/AppliedLessonRequestDTO.java
  src/main/java/com/ss/hanarowa/domain/lesson/dto/request/OfferedLessonRequestDTO.java
  src/main/java/com/ss/hanarowa/domain/lesson/service/LessonService.java
  src/main/java/com/ss/hanarowa/domain/lesson/service/impl/LessonServiceImpl.java
Labels: ⭐️ fix

#55 Fix :lesson category 추가
  src/main/java/com/ss/hanarowa/domain/lesson/controller/LessonController.java
  src/main/java/com/ss/hanarowa/domain/lesson/dto/response/LessonInfoResponseDTO.java
  src/main/java/com/ss/hanarowa/domain/lesson/service/impl/LessonServiceImpl.java
Labels: ⭐️ fix

#56 Feat: 시설 예약 목록 조회
  src/main/java/com/ss/hanarowa/domain/facility/controller/FacilityController.java
  src/main/java/com/ss/hanarowa/domain/facility/dto/reponse/FacilityReservationResponseDTO.java
  src/main/java/com/ss/hanarowa/domain/facility/repository/FacilityRepository.java
  src/main/java/com/ss/hanarowa/domain/facility/repository/FacilityTimeRepository.java
  src/main/java/com/ss/hanarowa/domain/facility/service/FacilityService.java
  src/main/java/com/ss/hanarowa/domain/facility/service/impl/FacilityServiceImpl.java
  src/main/java/com/ss/hanarowa/global/response/code/status/ErrorStatus.java
Labels: 🚀 feat

#69 Fix: 비로그인시 html 반환 에러 해결
  src/main/java/com/ss/hanarowa/global/config/CustomSecurityConfig.java
  src/main/java/com/ss/hanarowa/global/security/CustomAuthenticationEntryPoint.java
Labels: ⭐️ fix
