Repository SS-Soon-Senior/HanaroWa-BE, pull requests merged in 2025-09, with the labels that each got.

#84 Fix: 카카오 로그인 에러 수정
  src/main/java/com/ss/hanarowa/domain/member/controller/AuthController.java
  src/main/java/com/ss/hanarowa/global/config/CustomSecurityConfig.java
  src/main/java/com/ss/hanarowa/global/security/CustomOAuth2User.java
  src/main/java/com/ss/hanarowa/global/security/CustomOAuth2UserService.java
  src/main/java/com/ss/hanarowa/global/security/JwtAuthenticationFilter.java
  src/main/resources/application.properties
Labels: ⭐️ fix

#90 Refactor: refresh 토큰 쿠키에 저장
  src/main/java/com/ss/hanarowa/domain/member/controller/AuthController.java
  src/main/java/com/ss/hanarowa/domain/member/controller/JwtRefreshController.java
  src/main/java/com/ss/hanarowa/global/security/CustomOAuth2UserService.java
  src/main/java/com/ss/hanarowa/global/security/handler/OAuth2SuccessHandler.java
Labels: ⭐️ fix

#103 Feat:Lesson Room
  src/main/java/com/ss/hanarowa/domain/lesson/controller/LessonController.java
  src/main/java/com/ss/hanarowa/domain/lesson/dto/request/TimeAvailabilityRequestDTO.java
  src/main/java/com/ss/hanarowa/domain/lesson/dto/response/TimeAvailabilityResponseDTO.java
  src/main/java/com/ss/hanarowa/domain/lesson/repository/LessonRoomRepository.java
  src/main/java/com/ss/hanarowa/domain/lesson/repository/RoomTimeRepository.java
  src/main/java/com/ss/hanarowa/domain/lesson/service/LessonService.java
  src/main/java/com/ss/hanarowa/domain/lesson/service/impl/LessonServiceImpl.java
  src/main/java/com/ss/hanarowa/global/response/code/status/ErrorStatus.java
Labels: 🚀 feat

#106 Fix/lesson room
  src/main/java/com/ss/hanarowa/domain/lesson/dto/response/LessonGisuResponseDTO.java
  src/main/java/com/ss/hanarowa/domain/lesson/dto/response/LessonMoreDetailResponseDTO.java
  src/main/java/com/ss/hanarowa/domain/lesson/service/impl/AdminLessonServiceImpl.java
  src/main/java/com/ss/hanarowa/domain/lesson/service/impl/LessonServiceImpl.java
Labels: ⭐️ fix

#126 Fix: Create lesson request dto
  src/main/java/com/ss/hanarowa/domain/lesson/controller/AdminLessonController.java
  src/main/java/com/ss/hanarowa/domain/lesson/dto/request/CreateLessonRequestDTO.java
  src/main/java/com/ss/hanarowa/domain/lesson/dto/request/UpdateLessonGisuRequestDTO.java
  src/main/java/com/ss/hanarowa/domain/lesson/dto/response/LessonGisuDetailResponseDTO.java
  src/main/java/com/ss/hanarowa/domain/lesson/service/AdminLessonService.java
  src/main/java/com/ss/hanarowa/domain/lesson/service/impl/AdminLessonServiceImpl.java
  src/main/java/com/ss/hanarowa/domain/lesson/service/impl/LessonServiceImpl.java
Labels: 🚀 feat, ⭐️ fix

#129 Fix: token로직 전반적인 수정
  src/main/java/com/ss/hanarowa/domain/member/controller/AuthController.java
  src/main/java/com/ss/hanarowa/domain/member/controller/JwtRefreshController.java
  src/main/java/com/ss/hanarowa/domain/member/controller/MemberController.java
  src/main/java/com/ss/hanarowa/domain/member/dto/response/MemberInfoResponseDTO.java
  src/main/java/com/ss/hanarowa/global/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/ss/hanarowa/global/security/handler/CustomSuccessHandler.java
Labels: ⭐️ fix
